
document.getElementById('boton').onclick = function () {
    console.log("capturamos el evento click")
    document.getElementById("demo").innerHTML =  "Sin conocimientos en programación, esto es lo que pude lograr en un mes. Muchas gracias por la oprtunidad de aprendizaje. Espero seguir mejorando y pronto ser una profecional más 😁"
}
document.getElementById('estilo').onclick = function() {
    document.body.style.backgroundColor= ' hsl(0, 1%, 26%)'
}